# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-04 01:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicativo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estabelecimento',
            old_name='home',
            new_name='nome',
        ),
    ]
